<?php


namespace commands;

use Inhere\Console\IO\Input;
use Inhere\Console\IO\Output;
use interfaces\Console\CommandInterface;

class DemoCommand extends CommandInterface
{

    protected static $name = 'demo';
    protected static $description = 'this is a demo alone command. but config use configure(), like symfony console: argument define by position';

    protected function configure(): void
    {
        // TODO: Change the autogenerated stub
        parent::configure();
        $this->createDefinition()
            ->setExample($this->parseCommentsVars('{script} {command} john male 43 --opt1 value1'))
            ->addArgument('name', Input::ARG_REQUIRED, 'description for the argument [name], is required')
            ->addArgument('sex', Input::ARG_OPTIONAL, 'description for the argument [sex], is optional')
            ->addArgument('age', Input::ARG_OPTIONAL, 'description for the argument [age], is optional')
            ->addOption('yes', 'y', Input::OPT_BOOLEAN, 'description for the option [yes], is boolean')
            ->addOption('opt1', null, Input::OPT_REQUIRED, 'description for the option [opt1], is required')
            ->addOption('opt2', null, Input::OPT_OPTIONAL, 'description for the option [opt2], is optional');
    }

    /**
     * @inheritDoc
     */
    protected function execute($input, $output)
    {
        // TODO: Implement execute() method.
    }
}
