<?php


namespace commands;

use Inhere\Console\IO\Input;
use Inhere\Console\IO\Output;
use helper\Console\CommandInterface;

class DemoCommand extends CommandInterface
{

    protected static $name = 'demo';
    protected static $description = 'this is a demo alone command. but config use configure(), like symfony console: argument define by position';

    protected function configure(): void
    {
        // TODO: Change the autogenerated stub
        parent::configure();
        $this->createDefinition()
            ->setExample($this->parseCommentsVars('{script} {command} john male 43 --opt1 value1'));
    }

    /**
     * @inheritDoc
     */
    protected function execute($input, $output)
    {
        // TODO: Implement execute() method.
    }
}
