<?php


namespace commands;


use helper\Console\Command;
use Inhere\Console\IO\Input;
use Inhere\Console\IO\Output;

class ServerCommand extends Command
{

    protected static $name = 'server';
    protected static $description = 'server management';

    protected function configure(): void
    {
        // TODO: Change the autogenerated stub
        parent::configure();
        $this->createDefinition()
            ->setExample($this->parseCommentsVars('{script} {command}:[internet]'));
    }

    /**
     * @inheritDoc
     */
    protected function execute($input, $output)
    {
        // TODO: Implement execute() method.
    }
}
