<?php
declare(strict_types=1);

namespace app\bangtech\swoole_http\command;

use Inhere\Console\IO\Input;
use Inhere\Console\IO\Output;
use helper\Console\CommandInterface;

/**
 * Class DemoCommand
 * @package commands
 */
class DemoCommand extends CommandInterface
{
    // 命令名称
    protected static $name = 'bangtech:swoole_http:demo';
    // 命令描述
    protected static $description = 'This is a demo from bangtech/swoole_http';


    protected function configure(): void
    {
        // TODO: Change the autogenerated stub
        $this->createDefinition();
            //->addArgument('names',Input::ARG_REQUIRED,'name is admin');
    }


    /**
     * @param Input $input
     * @param Output $output
     * @return int|mixed|void
     */
    public function execute($input, $output)
    {

        $output->write('hello world, This is a demo from bangtech/swoole_http');
    }
}
