<?php

namespace app\demo\commands;

use Inhere\Console\IO\Input;
use Inhere\Console\IO\InputDefinition;
use Inhere\Console\IO\Output;
use helper\Console\CommandInterface;

/**
 * Class TestCommand
 * @package commands
 */
class DTestCommand extends CommandInterface
{
    // 命令名称
    protected static $name = 'dtest';
    // 命令描述
    protected static $description = 'this is a test independent command';

    public function __construct(Input $input, Output $output, InputDefinition $definition = null)
    {
        var_dump("hello");
        parent::__construct($input, $output, $definition);
    }

    protected function configure(): void
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->createDefinition()
            ->addArgument('names',Input::ARG_REQUIRED,'name is admin');
    }


    /**
     * @param Input $input
     * @param Output $output
     * @return int|mixed|void
     */
    public function execute($input, $output)
    {

        $output->write('hello, this in ');
    }
}
