<?php
declare(strict_types=1);

namespace app\bangtech\framework_ui\command;

use Inhere\Console\IO\Input;
use Inhere\Console\IO\Output;
use helper\Console\Command;

/**
 * Class DemoCommand
 * @package commands
 */
class DemoCommand extends Command
{
    // 命令名称
    protected static $name = 'bangtech:framework_ui:demo';
    // 命令描述
    protected static $description = 'This is a demo from bangtech/framework_ui';


    protected function configure(): void
    {
        // TODO: Change the autogenerated stub
        $this->createDefinition();
            //->addArgument('names',Input::ARG_REQUIRED,'name is admin');
    }


    /**
     * @param Input $input
     * @param Output $output
     * @return int|mixed|void
     */
    public function execute($input, $output)
    {

        $output->write('hello world, This is a demo from bangtech/framework_ui');
    }
}
